/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:26b003a1-3d60-4fa3-b1be-a41379bdc7bf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_o2ClWmkuM",
    "aws_user_pools_web_client_id": "ujvjemd6kb8rrqc530rnvoab8",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://py2pzanvxnfklm54vjmbvoixge.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7t6leiqmoncapcgy7pgc7gtzei",
    "aws_cloud_logic_custom": [
        {
            "name": "UsersApi",
            "endpoint": "https://u9rkl8sz1h.execute-api.us-east-1.amazonaws.com/sampledev",
            "region": "us-east-1"
        },
        {
            "name": "helloApi",
            "endpoint": "https://lcscc7m2j5.execute-api.us-east-1.amazonaws.com/sampledev",
            "region": "us-east-1"
        }
    ],
    "aws_mobile_analytics_app_id": "858fb76e10e64faa90b3ca22d698b3cd",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users-sampledev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
